TAB_MAPPING =
{
    ["0.0"] = {"Goomba Region"}, -- GR Forest Clearing
    ["0.1"] = {"Goomba Region"}, -- GR Foomba Village
    ["0.2"] = {"Goomba Region"}, -- GR Bottom of the Cliff
    ["0.3"] = {"Goomba Region"}, -- GR Jr. Troopa Playground
    ["0.4"] = {"Goomba Region"}, -- GR Behind the Village
    ["0.5"] = {"Goomba Region"}, -- GR 1
    ["0.6"] = {"Goomba Region"}, -- GR 2
    ["0.7"] = {"Goomba Region"}, -- GR 3
    ["0.8"] = {"Goomba Region"}, -- Toad Town Entrance (GR side)
    ["0.9"] = {"Goomba Region"}, -- Goomba King's Castle
    ["0.10"] = {"Goomba Region"}, -- GR 4
    ["0.11"] = {"Toad Town"}, -- Mario's House
    ["0.12"] = {"World Map"}, --Title Screen
    ["0.16"] = {"World Map"}, --Randomizer Setup Map
    ["0.17"] = {"World Map"}, -- Mario's House (Ending)
    ["1.0"] = {"Toad Town"}, -- Debug Warp ZOne
    ["1.1"] = {"Toad Town"}, -- Gate District
    ["1.2"] = {"Toad Town"}, -- Plaza District
    ["1.3"] = {"Toad Town"}, -- Southern District
    ["1.4"] = {"Toad Town"}, -- Station District
    ["1.5"] = {"Toad Town"}, -- Residential District
    ["1.6"] = {"Toad Town"}, -- Port District
    ["1.7"] = {"Toad Town"}, -- Riding the whale, could potentially be LLI
    ["2.0"] = {"Toad Town Tunnels"}, -- Warp Zone 1 (B1)
    ["2.1"] = {"Toad Town Tunnels"}, -- Blooper Boss 1 (B1)
    ["2.2"] = {"Toad Town Tunnels"}, -- Short Elevator Room (B1)
    ["2.3"] = {"Toad Town Tunnels"}, -- Scales Room (B2)
    ["2.4"] = {"Toad Town Tunnels"}, -- Spring Room (B2)
    ["2.5"] = {"Toad Town Tunnels"}, -- Sewer Entrance (B1)
    ["2.6"] = {"Toad Town Tunnels"}, -- Elevator Attic Room (B2)
    ["2.7"] = {"Toad Town Tunnels"}, -- Second Level Entry (B2)
    ["2.8"] = {"Toad Town Tunnels"}, -- Warp Zone 2 (B2)
    ["2.9"] = {"Toad Town Tunnels"}, -- Blue Pushblock Room (B2)
    ["2.10"] = {"Toad Town Tunnels"}, -- Metal Block Room (B3)
    ["2.11"] = {"Toad Town Tunnels"}, -- Rip Cheato Antechamber (B3)
    ["2.12"] = {"Toad Town Tunnels"}, -- Rip Cheato's Home (B3)
    ["2.13"] = {"Toad Town Tunnels"}, -- Frozen Room (B3)
    ["2.14"] = {"Toad Town Tunnels"}, -- Hall to Blooper 1 (B1)
    ["2.15"] = {"Toad Town Tunnels"}, -- Under the Toad Town Pond
    ["2.16"] = {"Toad Town Tunnels"}, -- Room with Spikes (B2)
    ["2.17"] = {"Toad Town Tunnels"}, -- Bridge to Shiver City (B2)
    ["2.18"] = {"Toad Town Tunnels"}, -- Pipe to Frozen Room (B2)
    ["2.19"] = {"Toad Town Tunnels"}, -- Winding Path (Spiny Room)
    ["2.20"] = {"Toad Town Tunnels"}, -- Hall to Ultra Boots (B3)
    ["2.21"] = {"Toad Town Tunnels"}, -- Ultra Boots Room (B3)
    ["3.0"] = {"Toad Town"}, -- Whale Mouth
    ["3.1"] = {"Toad Town"}, -- Whale Stomach
    ["4.4"] = {"Peach's Castle"}, -- PC Entry Hall 1F
    ["4.5"] = {"Peach's Castle"}, -- PC Upper Hall 2F
    ["4.6"] = {"Peach's Castle"}, -- PC Stairs Hallway 3F
    ["4.7"] = {"Peach's Castle"}, -- PC Window Hallway 4F
    ["4.8"] = {"Peach's Castle"}, -- PC Peach's Room 2F
    ["4.9"] = {"Peach's Castle"}, -- PC Passage Outlet 2F
    ["4.10"] = {"Peach's Castle"}, -- PC Library 2F
    ["4.11"] = {"Peach's Castle"}, -- PC Storeroom 2F
    ["4.12"] = {"Peach's Castle"}, -- PC Dining Room 2F
    ["4.13"] = {"Peach's Castle"}, -- PC Kitchen 1F
    ["4.14"] = {"Peach's Castle"}, -- PC Guest Room 1F
    ["4.15"] = {"Peach's Castle"}, -- PC Inactive Quiz-Off 1F
    ["4.16"] = {"Peach's Castle"}, -- PC Double Staircase 4F
    ["4.17"] = {"Peach's Castle"}, -- PC Rooftop 5F
    ["4.18"] = {"Peach's Castle"}, -- PC Tower Staircase 5F
    ["4.19"] = {"Peach's Castle"}, -- PC Final Boss Arena 6F
    ["4.20"] = {"Peach's Castle"}, -- Balcony 2F
    ["5.0"] = {"Toad Town"}, --Shooting Star Path
    ["5.1"] = {"Toad Town"}, --Shooting Star Summit
    ["5.2"] = {"Star Haven"}, --Star Way, to be verified
    ["5.3"] = {"Star Haven"}, --Star Haven
    ["5.4"] = {"Star Haven"}, --Outside the Sanctuary
    ["5.5"] = {"Star Haven"}, -- Star Sanctuary
    ["5.6"] = {"Toad Town"}, -- Merluvlee's House
    ["5.7"] = {"Star Haven"}, -- Riding Star Ship Scene
    ["6.0"] = {"Pleasant Path"}, -- Koopa Village 1
    ["6.1"] = {"Pleasant Path"}, -- Koopa Village 2
    ["6.2"] = {"Pleasant Path"}, -- Behind Koopa Village
    ["6.3"] = {"Pleasant Path"}, -- Fuzzy Forest
    ["6.4"] = {"Pleasant Path"}, -- Pleasant Path Entry
    ["6.5"] = {"Pleasant Path"}, -- Pleasant Path Bridge
    ["6.6"] = {"Pleasant Path"}, -- Pleasant Crossroads
    ["6.7"] = {"Pleasant Path"}, -- Path to Fortress 1
    ["6.8"] = {"Pleasant Path"}, -- Path to Fortress 2
    ["7.0"] = {"Koopa Bros. Fortress"}, -- Fortress Exterior
    ["7.1"] = {"Koopa Bros. Fortress"}, -- Left Tower
    ["7.2"] = {"Koopa Bros. Fortress"}, -- Left Stairway
    ["7.3"] = {"Koopa Bros. Fortress"}, -- Central Hall
    ["7.4"] = {"Koopa Bros. Fortress"}, -- Right Stairway
    ["7.5"] = {"Koopa Bros. Fortress"}, -- Right Tower
    ["7.6"] = {"Koopa Bros. Fortress"}, -- Jail
    ["7.7"] = {"Koopa Bros. Fortress"}, -- Dungeon Trap
    ["7.8"] = {"Koopa Bros. Fortress"}, -- Dungeon Fire Room
    ["7.9"] = {"Koopa Bros. Fortress"}, -- Battlement
    ["7.10"] = {"Koopa Bros. Fortress"}, --Boss Battle room
    ["8.0"] = {"Mt. Rugged"}, -- Mt. Rugged 1
    ["8.1"] = {"Mt. Rugged"}, -- Mt. Rugged 2
    ["8.2"] = {"Mt. Rugged"}, -- Mt. Rugged 3
    ["8.3"] = {"Mt. Rugged"}, -- Mt. Rugged 4
    ["8.4"] = {"Mt. Rugged"}, -- Suspension Bridge
    ["8.5"] = {"Mt. Rugged"}, -- Train Station
    ["8.6"] = {"Mt. Rugged"}, -- Train Ride scene
    ["9.0"] = {"Dry Dry Desert"},  -- Technically DDO, but on the same map
    ["9.1"] = {"Dry Dry Desert"}, -- Technically DDO
    ["10.0"] = {"Dry Dry Desert"}, --N3W3
    ["10.1"] = {"Dry Dry Desert"}, --N3W2
    ["10.2"] = {"Dry Dry Desert"}, --N3W1 Ruins Entrance
    ["10.3"] = {"Dry Dry Desert"}, --N3
    ["10.4"] = {"Dry Dry Desert"}, --N3E1
    ["10.5"] = {"Dry Dry Desert"}, --N3E2 Pokey Army
    ["10.6"] = {"Dry Dry Desert"}, --N3E3
    ["10.7"] = {"Dry Dry Desert"}, --N2W3
    ["10.8"] = {"Dry Dry Desert"}, --N2W2
    ["10.9"] = {"Dry Dry Desert"}, --N2W1
    ["10.10"] = {"Dry Dry Desert"}, --N2
    ["10.11"] = {"Dry Dry Desert"}, --N2E1 Tweester A
    ["10.12"] = {"Dry Dry Desert"}, --N2E2
    ["10.13"] = {"Dry Dry Desert"}, --N2E3
    ["10.14"] = {"Dry Dry Desert"}, --N1W3 Special Block
    ["10.15"] = {"Dry Dry Desert"}, --N1W2
    ["10.16"] = {"Dry Dry Desert"}, --N1W1
    ["10.17"] = {"Dry Dry Desert"}, --N1 Tweester B
    ["10.18"] = {"Dry Dry Desert"}, --N1E1 Palm Trio
    ["10.19"] = {"Dry Dry Desert"}, --N1E2
    ["10.20"] = {"Dry Dry Desert"}, --N1E3

    ["10.21"] = {"Dry Dry Desert"}, --W3 Kolorado's Camp
    ["10.22"] = {"Dry Dry Desert"}, --W2
    ["10.23"] = {"Dry Dry Desert"}, --W1
    ["10.24"] = {"Dry Dry Desert"}, --Center Tweester C

    ["10.25"] = {"Dry Dry Desert"}, --E1 Nomadimouse
    ["10.26"] = {"Dry Dry Desert"}, --E2
    ["10.27"] = {"Dry Dry Desert"}, --E3 Outside DDO
    ["10.28"] = {"Dry Dry Desert"}, --S1W3
    ["10.29"] = {"Dry Dry Desert"}, --S1W2 Tweester B
    ["10.30"] = {"Dry Dry Desert"}, --S1W1
    ["10.31"] = {"Dry Dry Desert"}, --S1 
    ["10.32"] = {"Dry Dry Desert"}, --S1E1
    ["10.33"] = {"Dry Dry Desert"}, --S1E2 Small Bluffs
    ["10.34"] = {"Dry Dry Desert"}, --S1E3 North of Oasis

    ["10.35"] = {"Dry Dry Desert"}, --S2W3
    ["10.36"] = {"Dry Dry Desert"}, --S2W2
    ["10.37"] = {"Dry Dry Desert"}, --S2W1
    ["10.38"] = {"Dry Dry Desert"}, --S2 
    ["10.39"] = {"Dry Dry Desert"}, --S2E1 Blue Cactus
    ["10.40"] = {"Dry Dry Desert"}, --S2E2 West of Oasis
    ["10.41"] = {"Dry Dry Desert"}, --S2E3 Oasis

    ["10.42"] = {"Dry Dry Desert"}, --S3W3
    ["10.43"] = {"Dry Dry Desert"}, --S3W2 Hidden AttackFX
    ["10.44"] = {"Dry Dry Desert"}, --S3W1
    ["10.45"] = {"Dry Dry Desert"}, --S3 
    ["10.46"] = {"Dry Dry Desert"}, --S3E1
    ["10.47"] = {"Dry Dry Desert"}, --S3E2
    ["10.48"] = {"Dry Dry Desert"}, --S3E3 South of Oasis
    ["10.49"] = {"Dry Dry Desert"}, --Entrance
  
    -- DDR
    ["11.0"] = {"Dry Dry Ruins"}, -- Entrance
    ["11.1"] = {"Dry Dry Ruins"}, -- Sarcophagus Hall 1
    ["11.2"] = {"Dry Dry Ruins"}, -- Sand Draininage Room 1
    ["11.3"] = {"Dry Dry Ruins"}, -- Descending Stairs 1
    ["11.4"] = {"Dry Dry Ruins"}, -- Pyramid Stone Room
    ["11.5"] = {"Dry Dry Ruins"}, -- Sand Drainage Room 2
    ["11.6"] = {"Dry Dry Ruins"}, -- Sarcophagus Hall 2
    ["11.7"] = {"Dry Dry Ruins"}, -- Descending Stairs 2
    ["11.8"] = {"Dry Dry Ruins"}, -- Super Hammer Room
    ["11.9"] = {"Dry Dry Ruins"}, -- Vertical Shaft
    ["11.10"] = {"Dry Dry Ruins"}, -- Stone Puzzle Room
    ["11.11"] = {"Dry Dry Ruins"}, -- Sand Drainage Room 3
    ["11.12"] = {"Dry Dry Ruins"}, -- Lunar Stone Room
    ["11.13"] = {"Dry Dry Ruins"}, -- Diamond Stone Room
    ["11.14"] = {"Dry Dry Ruins"}, -- Tutankoopa Room
    ["11.15"] = {"Dry Dry Ruins"}, -- Deep Tunnel
    ["11.16"] = {"Dry Dry Ruins"}, -- Boss Antechamber
    -- Forever forest
    ["12.0"] = {"Forever Forest"}, -- Flower Sounds
    ["12.1"] = {"Forever Forest"}, -- Stump Eyes
    ["12.2"] = {"Forever Forest"}, -- Flowers (Oaklie)
    ["12.3"] = {"Forever Forest"}, -- Tree Face (Bub-ulb)
    ["12.4"] = {"Forever Forest"}, -- Mushrooms (Path Splits)
    ["12.5"] = {"Forever Forest"}, -- Flowers Vanish
    ["12.6"] = {"Forever Forest"}, -- Laughing Rock
    ["12.7"] = {"Forever Forest"}, -- Bee Hive (HP Plus)
    ["12.8"] = {"Forever Forest"}, -- Flowers Appear (FP Plus)
    ["12.9"] = {"Forever Forest"}, -- Exit to Toad Town
    ["12.10"] = {"Boo's Mansion"}, -- Outside Boo's Mansion
    ["12.11"] = {"Gusty Gulch"}, -- Exit to Gusty Gulch
    -- Boo's Mansion
    ["13.0"] = {"Boo's Mansion"}, -- Foyer
    ["13.1"] = {"Boo's Mansion"}, -- Basement Stairs
    ["13.2"] = {"Boo's Mansion"}, -- Basement
    ["13.3"] = {"Boo's Mansion"}, -- Super Boots Room
    ["13.4"] = {"Boo's Mansion"}, -- Pot Room
    ["13.5"] = {"Boo's Mansion"}, -- Library
    ["13.6"] = {"Boo's Mansion"}, -- Record Player Room
    ["13.7"] = {"Boo's Mansion"}, -- Record Room
    ["13.8"] = {"Boo's Mansion"}, -- Lady Bow's Room
    -- Gusty Gulch
    ["14.0"] = {"Gusty Gulch"}, -- Wasteland Ascent 1
    ["14.1"] = {"Gusty Gulch"}, -- Ghost Town 1
    ["14.2"] = {"Gusty Gulch"}, -- Wasteland Ascent 2
    ["14.3"] = {"Gusty Gulch"}, -- Ghost Town 2
    ["14.4"] = {"Gusty Gulch"}, -- Windmill Exterior
    ["14.5"] = {"Gusty Gulch"}, -- Windmill Interior
    ["14.6"] = {"Gusty Gulch"}, -- Windmill Tunnel Entry
    ["14.7"] = {"Gusty Gulch"}, -- Tunnel 1
    ["14.8"] = {"Gusty Gulch"}, -- Tubba's Heart CHamber
    ["14.9"] = {"Gusty Gulch"}, -- Tunnel 2
    ["14.10"] = {"Gusty Gulch"}, -- Tunnel 3
    -- Tubba's Castle
    ["15.0"] = {"Tubba's Castle"}, --  Outside Tubba's Castle
    ["15.1"] = {"Tubba's Castle"}, -- Great Hall
    ["15.2"] = {"Tubba's Castle"}, -- West Hall 1F
    ["15.3"] = {"Tubba's Castle"}, -- Table/Clock Room (1/2F)
    ["15.4"] = {"Tubba's Castle"}, -- Stairs to Basement
    ["15.5"] = {"Tubba's Castle"}, -- Stairs Above Basement
    ["15.6"] = {"Tubba's Castle"}, -- Basement
    ["15.7"] = {"Tubba's Castle"}, -- Study 1F
    ["15.8"] = {"Tubba's Castle"}, -- East Hall (1/2F)
    ["15.9"] = {"Tubba's Castle"}, -- West Hall (2F)
    ["15.10"] = {"Tubba's Castle"}, -- Sealed Room (2F)
    ["15.11"] = {"Tubba's Castle"}, -- Covered Tables Room (1F)
    ["15.12"] = {"Tubba's Castle"}, -- Spike Trap Room (2F)
    ["15.13"] = {"Tubba's Castle"}, -- Hidden Bedroom (2F)
    ["15.14"] = {"Tubba's Castle"}, -- Stairs to Third Floor
    ["15.15"] = {"Tubba's Castle"}, -- West Hall (3F)
    ["15.16"] = {"Tubba's Castle"}, -- Sleeping Clubbas Room (3F)
    ["15.17"] = {"Tubba's Castle"}, -- Save Room (3F)
    ["15.18"] = {"Tubba's Castle"}, -- Master Bedroom (3F)
    --16 SGT
    ["16.0"] = {"Shy Guy's Toy Box"}, -- BLU Large Playroom
    ["16.1"] = {"Shy Guy's Toy Box"}, -- RED Boss Barricade
    ["16.2"] = {"Shy Guy's Toy Box"}, -- BLU Station
    ["16.3"] = {"Shy Guy's Toy Box"}, -- BLU Block City
    ["16.4"] = {"Shy Guy's Toy Box"}, -- PNK Gourmet Guy Crossing
    ["16.5"] = {"Shy Guy's Toy Box"}, -- PNK Station
    ["16.6"] = {"Shy Guy's Toy Box"}, -- PNK Playhouse
    ["16.7"] = {"Shy Guy's Toy Box"}, -- GRN Station
    ["16.8"] = {"Shy Guy's Toy Box"}, -- GRN Treadmills/Slot Machine
    ["16.9"] = {"Shy Guy's Toy Box"}, -- RED Station
    ["16.10"] = {"Shy Guy's Toy Box"}, -- RED Moving Platforms
    ["16.11"] = {"Shy Guy's Toy Box"}, -- RED Lantern Ghost
    ["16.12"] = {"Shy Guy's Toy Box"}, -- BLU Anti-Guy Hall
    ["16.13"] = {"Shy Guy's Toy Box"}, -- RED Boss Antechamber
    ["16.14"] = {"Shy Guy's Toy Box"}, -- RED General Guy Room
    ["16.16"] = {"Shy Guy's Toy Box"}, -- PNK Tracks Hallway
    --17 Lavalava island
    ["17.0"] = {"Jade Jungle"}, -- Whale Cove
    ["17.1"] = {"Jade Jungle"}, -- Beach
    ["17.2"] = {"Jade Jungle"}, -- Village Cove
    ["17.3"] = {"Jade Jungle"}, -- Village Buildings
    ["17.4"] = {"Jade Jungle"}, -- Sushi Tree
    ["17.5"] = {"Jade Jungle"}, -- SE Jungle (Quake Hammer)
    ["17.6"] = {"Jade Jungle"}, -- NE Jungle (Raven Statue)
    ["17.7"] = {"Jade Jungle"}, -- Small Jungle Ledge
    ["17.8"] = {"Jade Jungle"}, -- SW Jungle (Super Block)
    ["17.9"] = {"Jade Jungle"}, -- NW Jungle (Large Ledge)
    ["17.10"] = {"Jade Jungle"}, -- Western Dead End
    ["17.11"] = {"Jade Jungle"}, -- Root Cavern
    ["17.12"] = {"Jade Jungle"}, -- Deep Jungle 1
    ["17.13"] = {"Jade Jungle"}, -- Deep Jungle 2 (Block Puzzle)
    ["17.14"] = {"Jade Jungle"}, -- Deep Jungle 3 
    ["17.15"] = {"Jade Jungle"}, -- Deep Jungle 4 (Ambush)
    ["17.16"] = {"Jade Jungle"}, -- Base of great Tree
    ["17.17"] = {"Jade Jungle"}, -- Lower Great Tree Interior
    ["17.18"] = {"Jade Jungle"}, -- Great Tree Vine Ascent
    ["17.19"] = {"Jade Jungle"}, -- Upper Great Tree Interior
    ["17.20"] = {"Jade Jungle"}, -- Path to the Volcano
    ["17.21"] = {"Jade Jungle"}, -- Great Treetop Roost
    --18 Mt. Lavalava
    ["18.0"] = {"Mt. Lavalava"}, -- Volcano Entrance
    ["18.1"] = {"Mt. Lavalava"}, -- First Lava Lake
    ["18.2"] = {"Mt. Lavalava"}, -- Central Cavern
    ["18.3"] = {"Mt. Lavalava"}, -- Fire Bar Bridge
    ["18.4"] = {"Mt. Lavalava"}, -- Descent Toward Ultra Hammer
    ["18.5"] = {"Mt. Lavalava"}, -- Flowing Lava Puzzle
    ["18.6"] = {"Mt. Lavalava"}, -- Ultra Hammer Room
    ["18.7"] = {"Mt. Lavalava"}, -- Dizzy Stomp Room
    ["18.8"] = {"Mt. Lavalava"}, -- Zipline Cavern
    ["18.9"] = {"Mt. Lavalava"}, -- Descent Toward Boss
    ["18.10"] = {"Mt. Lavalava"}, -- Second lava Lake
    ["18.11"] = {"Mt. Lavalava"}, -- Spike Roller Trap
    ["18.12"] = {"Mt. Lavalava"}, -- Boss Antechamber
    ["18.13"] = {"Mt. Lavalava"}, -- Boss Room
    ["18.14"] = {"Mt. Lavalava"}, -- Rising Lava 1
    ["18.15"] = {"Mt. Lavalava"}, -- Rising Lava 2
    -- 19 Flower Fields
    ["19.0"] = {"Flower Fields"}, -- Center
    ["19.1"] = {"Flower Fields"}, -- (East) Petunia's Field
    ["19.2"] = {"Flower Fields"}, -- (SW) Posie and Crystal Tree
    ["19.3"] = {"Flower Fields"}, -- (SE) Briar Platforming
    ["19.4"] = {"Flower Fields"}, -- (East) Triple Tree Path
    ["19.5"] = {"Flower Fields"}, -- (SE) Lily's Fountain
    ["19.6"] = {"Flower Fields"}, -- (West) Maze
    ["19.7"] = {"Flower Fields"}, -- (West) Rosie's Trellis
    ["19.8"] = {"Flower Fields"}, -- (NW) Lakilester
    ["19.9"] = {"Flower Fields"}, -- (NW) Bubble Flower
    ["19.10"] = {"Flower Fields"}, -- (NW) Sun Tower
    ["19.11"] = {"Flower Fields"}, -- (NE) Elevators
    ["19.12"] = {"Flower Fields"}, -- (NE) Fallen Logs
    ["19.13"] = {"Flower Fields"}, -- (NE) Puff Puff Machine
    ["19.14"] = {"Flower Fields"}, -- Cloudy Climb
    ["19.15"] = {"Flower Fields"}, -- Huff N Puff Room
    ["19.16"] = {"Flower Fields"}, -- (East) Old Well
    ["19.17"] = {"Flower Fields"}, -- (West) Path to Maze
    ["19.18"] = {"Flower Fields"}, -- (SE) Water Level Room
    ["19.19"] = {"Flower Fields"}, -- (SW) Path to Crystal Tree
    -- Shiver Region
    ["20.0"] = {"Shiver Region"}, -- Shiver City Mayor Area
    ["20.1"] = {"Shiver Region"}, -- Shiver City Center
    ["20.2"] = {"Shiver Region"}, -- Road to Shiver Snowfield
    ["20.3"] = {"Shiver Region"}, -- Shiver Snowfield
    ["20.4"] = {"Shiver Region"}, -- Path to Starborn Valley
    ["20.5"] = {"Shiver Region"}, -- Starborn Valley
    ["20.6"] = {"Shiver Region"}, -- Shiver Mountain Passage
    ["20.7"] = {"Shiver Region"}, -- Shiver Mountain Hills
    ["20.8"] = {"Shiver Region"}, -- Shiver Mountain Tunnel
    ["20.9"] = {"Shiver Region"}, -- Shiver Mountain Peaks
    ["20.10"] = {"Shiver Region"}, -- Shiver City Pond Area
    ["20.11"] = {"Shiver Region"}, -- Merlar's Sanctuary
    -- Crystal Palace
    ["21.0"] = {"Crystal Palace"}, -- Entrance
    ["21.1"] = {"Crystal Palace"}, -- Entry Hall
    ["21.2"] = {"Crystal Palace"}, -- Save Room
    ["21.3"] = {"Crystal Palace"}, -- Reflected Save Room
    ["21.4"] = {"Crystal Palace"}, -- Blue Key Room
    ["21.5"] = {"Crystal Palace"}, -- Shooting Star Room
    ["21.6"] = {"Crystal Palace"}, -- Red Key Hall
    ["21.7"] = {"Crystal Palace"}, -- P-Down D-Up Hall
    ["21.8"] = {"Crystal Palace"}, -- Red Key Room
    ["21.9"] = {"Crystal Palace"}, -- P-Down D-Up Room
    ["21.10"] = {"Crystal Palace"}, -- Blue Mirror Hall 1
    ["21.11"] = {"Crystal Palace"}, -- Blue Mirror Hall 2
    ["21.12"] = {"Crystal Palace"}, -- Star Piece Cave
    ["21.13"] = {"Crystal Palace"}, -- Red Mirror Hall
    ["21.14"] = {"Crystal Palace"}, -- Bridge Mirror Hall
    ["21.15"] = {"Crystal Palace"}, -- Reflection Mimic Room
    ["21.16"] = {"Crystal Palace"}, -- Mirrored Door Room
    ["21.17"] = {"Crystal Palace"}, -- Huge Statue Room
    ["21.18"] = {"Crystal Palace"}, -- Small Statue Room
    ["21.19"] = {"Crystal Palace"}, -- Palace Key Room
    ["21.20"] = {"Crystal Palace"}, -- P-Up D-Down Room
    ["21.21"] = {"Crystal Palace"}, -- Hidden Bridge Room
    ["21.22"] = {"Crystal Palace"}, -- Dino Puzzle Room
    ["21.23"] = {"Crystal Palace"}, -- Crystal Summit
    ["21.24"] = {"Crystal Palace"}, -- Turnstyle Room
    ["21.25"] = {"Crystal Palace"}, -- Mirror Hole Room
    ["21.26"] = {"Crystal Palace"}, -- Triple Dip Room
    ["21.27"] = {"Crystal Palace"}, -- Palace Key Hall
    ["21.28"] = {"Crystal Palace"}, -- P-Up D-Down Hall
    ["21.29"] = {"Crystal Palace"}, -- Blue Key Hall
    ["21.30"] = {"Crystal Palace"}, -- Shooting Star Hall
    ["21.31"] = {"Crystal Palace"}, -- Boss Antechamber
    -- Bowser's Castle
    ["22.0"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Dark Cave 1
    ["22.1"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Dark Cave 2
    ["22.2"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Cave Exit
    ["22.3"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Castle Key Timing Puzzle
    ["22.4"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Ultra Shroom Timing Puzzle
    ["22.5"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Outside Lower Jail
    ["22.6"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Outside Lower Jail
    ["22.7"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lava Channel 1
    ["22.8"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lava Channel 2
    ["22.9"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lava Channel 3
    ["22.10"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lava Key Room
    ["22.11"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lava Control Room
    ["22.12"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Lower Jail
    ["22.13"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Lower Grand Hall
    ["22.14"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Upper Grand Hall
    ["22.15"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Maze Guide Room
    ["22.16"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Maze Room
    ["22.17"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Hall to Guard Door 1
    ["22.18"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Hall to Water Puzzle
    ["22.19"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Split Level Hall
    ["22.20"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Fake Peach Hallway
    ["22.21"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Ship Enter/Exit Scenes
    ["22.22"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Battlement
    ["22.23"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Front Door Exterior
    ["22.24"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Hangar
    ["22.25"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Entry Lava Hall
    ["22.26"] = {"Bowser's Castle","Before Quiz Door 1"}, -- Guard Door 1
    ["22.27"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Guard Door 2
    ["22.28"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Guard Door 3
    ["22.29"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Stairs to East Upper Jail
    ["22.30"] = {"Bowser's Castle","Before Quiz Door 2"}, -- East Upper Jail
    ["22.31"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Stairs to West Upper Jail
    ["22.32"] = {"Bowser's Castle","Before Quiz Door 3"}, -- West Upper Jail
    ["22.33"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Item Shop
    ["22.34"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Castle Key Room
    ["22.35"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Ultra Shroom Room
    ["22.36"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Blue Fire Bridge
    ["22.37"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Room with hidden Door 1
    ["22.38"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Hidden Passage 1
    ["22.39"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Room with hidden Door 2
    ["22.40"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Hidden Passage 2
    ["22.41"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Room with hidden Door 3
    ["22.42"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Dead End Passage
    ["22.43"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Dead End Room
    ["22.44"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Hidden Passage 3
    ["22.45"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Hidden Key Room
    ["22.46"] = {"Bowser's Castle","Before Quiz Door 3"}, -- Exit to Peach's Castle
    ["22.47"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Bill Blaster Hall
    ["22.48"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Left Water Puzzle
    ["22.49"] = {"Bowser's Castle","Before Quiz Door 2"}, -- Right Water Puzzle
    -- Peach castle grounds
    ["23.1"] = {"Toad Town"}, -- Peach's Castle Grounds
    ["23.2"] = {"Peach's Castle"}, -- Peach's Castle Grounds
    --Credits
    ["24.0"] = {"World Map"}, -- Credits
    ["24.1"] = {"World Map"}, -- Credits
    --Play room
    ["25.0"] = {"Toad Town"}, -- Playroom
    ["25.1"] = {"Toad Town"}, -- Playroom
    ["25.2"] = {"Toad Town"}, -- Playroom
    --Game over
    ["26.0"] = {"World Map"}, -- Game Over

     
}